### ISSUE TITLE
Table cannot be updated when a new row inserted

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [pybee/toga-cocoa#3]
When I call the inserted method for table Widget after the app startup, the table will not show the new row. However, on linux, it works fine.

**Comment by freakboy3742** [comment]
Thanks for the report. The API for the table widget hasn't stabilised yet, so I'm not entirely surprised that there are bugs. 

However, the good news is that the code is pretty simple to dig into, so if you want to help out, this would be a great way to contribute!

**Comment by Xuefeng-Zhu** [comment]
Thanks for quick response. Currently, I am using this library for my assignment, which will be due soon. I  am afraid that I will not have much time to dig into the bugs. Could you please several suggestions to fix them? Thanks.

**Comment by Xuefeng-Zhu** [comment]
I check the data list in Table object, and it actually got the row I inserted, but it just did not display it.

**Comment by freakboy3742** [comment]
To be completely honest, Toga probably isn't a good choice for a university assignment, unless your project is to fix bugs in someone else's project. It's not a mature widget framework - it's a work in progress. 

If you're looking for hints on bug fixing, you're going to need to be familiar with the raw OS/X Cocoa APIs. Toga is a pretty light wrapper around those; I'm guessing there's some sort of "refresh" call missing here, but without digging into the problem, I can't offer any more concrete advice.

**Comment by Xuefeng-Zhu** [comment]
OK. Thanks. Will Toga perform better on Windows?

**Comment by freakboy3742** [comment]
Ah, No. 

Windows support is a complete afterthought. I added a win32 backend so that I could prove it could be done in theory, but in practice, you can put a button the screen, and that's about it. Cocoa is the most mature backend by a long way.

**Comment by Xuefeng-Zhu** [comment]
Thanks for your help. I think this is a very elegant GUI lib for python. Probably, you can apply for google summer code next year to
