### ISSUE TITLE
Scroll windows lose content on scroll

### ISSUE THREAD

**Issue by freakboy3742** [pybee/toga-cocoa#9]
Using the development branch (labelled as 0.2.0, but not released to PyPI):

If you start the toga demo, all the widgets are displayed, and respond to button clicks as expected.

If you resize the window, the widgets resize as expected.

However, if you attempt scroll the right hand panel (the one with all the buttons in it), the contents of the scroll window disappear.

I'm guessing either the document view or the content view are being resized to 0 size - but I can't work out where that is happening.

**Comment by marcmolla** [comment]
I tried to reproduce this issue but it is working fine for me. I did two tests: one with only toga-cocoa from tag v0.2.0 and another with all toga packages from this dev tag.

Could be the issue in other package?

**Comment by freakboy3742** [comment]
@marcmolla Interesting - just to confirm: you can start toga-demo, and all the widgets display, including the right hand side of the split-panel, which has a set of buttons labelled "hello world 0" through "hello world 9"; and this right hand side panel can be scrolled without the buttons disappearing. Could you provide a screen shot so I can confirm you're seeing what I think you should be seeing?

Also - can you tell me what version of macOS you're running?

**Comment by marcmolla** [comment]
Yes, that is the test I did. 
The initial app screen is:
<img width="644" alt="initial_screen" src="https://cloud.githubusercontent.com/assets/3853921/18267240/73e8c86a-741e-11e6-9b59-0d7233ef93c3.png">
I only noticed that the buttons are not labelled with a number (and the toga icon is missing :), this error is solved in the pip version of toga-demo)
I resized the app and scrolled down the right panel and I still saw the buttons:
<img width="1068" alt="resized_and_scroll_down" src="https://cloud.githubusercontent.com/assets/3853921/18267258/85d07672-741e-11e6-9716-aa9d7177adfa.png">

My python 3.5 environment is (I am using an environment of anaconda):
(pybee) iMac-de-Marc:toga-demo marc$ pip list
colosseum (0.1.2)
pip (8.1.2)
rubicon-objc (0.2.2)
setuptools (26.1.1)
toga (0.2.0)
toga-cocoa (0.2.0)
toga-core (0.2.0)
toga-demo (0.2.0)
wheel (0.29.0)

All toga packages are from git branch v0.2.0.

My OS X version is 10.11.6

**Comment by freakboy3742** [comment]
Well this is just *odd*. That's exactly the same version of OS X that I have, but I don't get the buttons rendered on the right hand panel.

I'll put a call out to see if anyone else can reproduce this problem (or success).

**Comment by AzMoo** [comment]
No buttons on the right-hand panel for me.

<img width="993" alt="screen shot 2016-09-07 at 2 45 17 pm" src="https://cloud.githubusercontent.com/assets/174400/18300617/d036a8ee-7509-11e6-8915-fb66b0926813.png">

colosseum (0.1.2)
pip (8.1.2)
rubicon-objc (0.2.2)
setuptools (18.2)
toga (0.2.0)
toga-cocoa (0.2.0)
toga-core (0.2.0)
toga-demo (0.2.0)

OSX 10.11.6

**Comment by jarshwah** [comment]
No buttons on the right for me. If I expand the entire window diagonally larger, multiple hello world buttons appear. Shrunk the window slightly, received scroll bar. Scrolled all the way to the bottom, lose scroll bar and buttons. Unable to get them back.

**Comment by zenlc2000** [comment]
Buttons showed up fine for me both before and after scrolling. Also fine after resize and scroll.

OSX 10.11.6
Anaconda Python 3.5.2-0
Fresh env & toga-demo

**Comment by FuzzAU** [comment]
Python 3.5.2, OS X 10.11.6. Can scroll all day long, before and after resize, without disappearance

<img width="798" alt="screen shot 2016-09-07 at 3 24 50 pm" src="https://cloud.githubusercontent.com/assets/1161763/18300728/48ab7aac-750f-11e6-8682-ccc107d2b1b6.png">

**Comment by glasnt** [comment]
I get the same as hawkowl, but using a different python version. 

Python 3.5.1, OSX 10.11.6 (15G1004), fresh venv 

No buttons until I resize the window long enough, and then they appear. Resize to make the window shorter so that the scroll bar appears, then scroll down, and they disappear.

**Comment by freakboy3742** [comment]
Ok... I think the only reasonable conclusion at this point is "OSX is possessed." 👿

**Comment by tleeuwenburg** [comment]
No matter what I do, I don't see the right panel or any button.

Successfully installed colosseum-0.1.2 rubicon-objc-0.2.2 toga-0.2.0 toga-cocoa-0.2.0 toga-core-0.2.0 toga-demo-0.2.0

**Comment by Dude-X** [comment]
I followed the instructions on twitter; I get a UI with no Hello World Buttons.
OS X 10.11.6
Brew Python 3.5.2
colosseum (0.1.2)
pip (8.1.2)
rubicon-objc (0.2.2)
setuptools (26.1.1)
toga (0.2.0)
toga-cocoa (0.2.0)
toga-core (0.2.0)
toga-demo (0.2.0)
wheel (0.29.0)

The following output is displayed when I start `toga-demo`.
```
open file  <ObjCInstance 0x1149a3eb8: __NSArrayI at 140726978678016>
OPEN /Users/ivargas/venv/beeware/bin/toga-demo
convert /Users/ivargas/venv/beeware/bin/toga-demo to URL
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/Users/ivargas/venv/beeware/lib/python3.5/site-packages/rubicon/objc/objc.py", line 1003, in _objc_method
    result = f(py_self, *args)
  File "/Users/ivargas/venv/beeware/lib/python3.5/site-packages/toga_cocoa/app.py", line 67, in application_openFiles_
    self._interface.open_document(fileURL.absoluteString)
  File "/Users/ivargas/venv/beeware/lib/python3.5/site-packages/toga/interface/app.py", line 45, in open_document
    raise NotImplementedError('Application class must define open_document()')
NotImplementedError: Application class must define open_document()
```

**Comment by jeamland** [comment]
No buttons at startup but they appear after any resize. I'm also getting the same exception output as @Dude-X.

OS X 10.11.6 + security patch.

Brew Python 3.5.2:

    Python 3.5.2 (default, Aug 16 2016, 05:35:40)
    [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.

pip freeze:

    colosseum==0.1.2
    rubicon-objc==0.2.2
    toga==0.2.0
    toga-cocoa==0.2.0
    toga-core==0.2.0
    toga-demo==0.2.0
